using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace XamlMVVMInfrastructure.WpfLib
{
    public class KeyMapping
    {
        public static MVVMInfrastructure.Key Map(System.Windows.Input.Key key)
        {
            switch (key)
            {
                case System.Windows.Input.Key.None:
                    return MVVMInfrastructure.Key.None;
                case System.Windows.Input.Key.Cancel:
                    return MVVMInfrastructure.Key.Cancel;
                case System.Windows.Input.Key.Back:
                    return MVVMInfrastructure.Key.Back;
                case System.Windows.Input.Key.Tab:
                    return MVVMInfrastructure.Key.Tab;
                //case System.Windows.Input.Key.LineFeed:
                //    return MVVMInfrastructure.Key.LineFeed;
                case System.Windows.Input.Key.Clear:
                    return MVVMInfrastructure.Key.Clear;
                //case System.Windows.Input.Key.Return:
                //    return MVVMInfrastructure.Key.Return;
                case System.Windows.Input.Key.Enter:
                    return MVVMInfrastructure.Key.Enter;
                case System.Windows.Input.Key.Pause:
                    return MVVMInfrastructure.Key.Pause;
                //case System.Windows.Input.Key.Capital:
                //    break;
                case System.Windows.Input.Key.CapsLock:
                    return MVVMInfrastructure.Key.CapsLock;
                //case System.Windows.Input.Key.KanaMode:
                //    break;
                //case System.Windows.Input.Key.HangulMode:
                //    break;
                //case System.Windows.Input.Key.JunjaMode:
                //    break;
                //case System.Windows.Input.Key.FinalMode:
                //    break;
                //case System.Windows.Input.Key.HanjaMode:
                //    break;
                //case System.Windows.Input.Key.KanjiMode:
                //    break;
                case System.Windows.Input.Key.Escape:
                    return MVVMInfrastructure.Key.Escape;
                case System.Windows.Input.Key.ImeConvert:
                    return MVVMInfrastructure.Key.ImeConvert;
                case System.Windows.Input.Key.ImeNonConvert:
                    return MVVMInfrastructure.Key.ImeNonConvert;
                case System.Windows.Input.Key.ImeAccept:
                    return MVVMInfrastructure.Key.ImeAccept;
                case System.Windows.Input.Key.ImeModeChange:
                    return MVVMInfrastructure.Key.ImeModeChange;
                case System.Windows.Input.Key.Space:
                    return MVVMInfrastructure.Key.Space;
                //case System.Windows.Input.Key.Prior:
                //    break;
                case System.Windows.Input.Key.PageUp:
                    return MVVMInfrastructure.Key.PageUp;
                //case System.Windows.Input.Key.Next:
                //    break;
                case System.Windows.Input.Key.PageDown:
                    return MVVMInfrastructure.Key.PageDown;
                case System.Windows.Input.Key.End:
                    return MVVMInfrastructure.Key.End;
                case System.Windows.Input.Key.Home:
                    return MVVMInfrastructure.Key.Home;
                case System.Windows.Input.Key.Left:
                    return MVVMInfrastructure.Key.Left;
                case System.Windows.Input.Key.Up:
                    return MVVMInfrastructure.Key.Up;
                case System.Windows.Input.Key.Right:
                    return MVVMInfrastructure.Key.Right;
                case System.Windows.Input.Key.Down:
                    return MVVMInfrastructure.Key.Down;
                case System.Windows.Input.Key.Select:
                    return MVVMInfrastructure.Key.Select;
                case System.Windows.Input.Key.Print:
                    return MVVMInfrastructure.Key.Print;
                case System.Windows.Input.Key.Execute:
                    return MVVMInfrastructure.Key.Execute;
                //case System.Windows.Input.Key.Snapshot:
                //    break;
                case System.Windows.Input.Key.PrintScreen:
                    return MVVMInfrastructure.Key.PrintScreen;
                case System.Windows.Input.Key.Insert:
                    return MVVMInfrastructure.Key.Insert;
                case System.Windows.Input.Key.Delete:
                    return MVVMInfrastructure.Key.Delete;
                case System.Windows.Input.Key.Help:
                    return MVVMInfrastructure.Key.Help;
                case System.Windows.Input.Key.D0:
                    return MVVMInfrastructure.Key.D0;
                case System.Windows.Input.Key.D1:
                    return MVVMInfrastructure.Key.D1;
                case System.Windows.Input.Key.D2:
                    return MVVMInfrastructure.Key.D2;
                case System.Windows.Input.Key.D3:
                    return MVVMInfrastructure.Key.D3;
                case System.Windows.Input.Key.D4:
                    return MVVMInfrastructure.Key.D4;
                case System.Windows.Input.Key.D5:
                    return MVVMInfrastructure.Key.D5;
                case System.Windows.Input.Key.D6:
                    return MVVMInfrastructure.Key.D6;
                case System.Windows.Input.Key.D7:
                    return MVVMInfrastructure.Key.D7;
                case System.Windows.Input.Key.D8:
                    return MVVMInfrastructure.Key.D8;
                case System.Windows.Input.Key.D9:
                    return MVVMInfrastructure.Key.D9;
                case System.Windows.Input.Key.A:
                    return MVVMInfrastructure.Key.A;
                case System.Windows.Input.Key.B:
                    return MVVMInfrastructure.Key.B;
                case System.Windows.Input.Key.C:
                    return MVVMInfrastructure.Key.C;
                case System.Windows.Input.Key.D:
                    return MVVMInfrastructure.Key.D;
                case System.Windows.Input.Key.E:
                    return MVVMInfrastructure.Key.E;
                case System.Windows.Input.Key.F:
                    return MVVMInfrastructure.Key.F;
                case System.Windows.Input.Key.G:
                    return MVVMInfrastructure.Key.G;
                case System.Windows.Input.Key.H:
                    return MVVMInfrastructure.Key.H;
                case System.Windows.Input.Key.I:
                    return MVVMInfrastructure.Key.I;
                case System.Windows.Input.Key.J:
                    return MVVMInfrastructure.Key.J;
                case System.Windows.Input.Key.K:
                    return MVVMInfrastructure.Key.K;
                case System.Windows.Input.Key.L:
                    return MVVMInfrastructure.Key.L;
                case System.Windows.Input.Key.M:
                    return MVVMInfrastructure.Key.M;
                case System.Windows.Input.Key.N:
                    return MVVMInfrastructure.Key.N;
                case System.Windows.Input.Key.O:
                    return MVVMInfrastructure.Key.O;
                case System.Windows.Input.Key.P:
                    return MVVMInfrastructure.Key.P;
                case System.Windows.Input.Key.Q:
                    return MVVMInfrastructure.Key.Q;
                case System.Windows.Input.Key.R:
                    return MVVMInfrastructure.Key.R;
                case System.Windows.Input.Key.S:
                    return MVVMInfrastructure.Key.S;
                case System.Windows.Input.Key.T:
                    return MVVMInfrastructure.Key.T;
                case System.Windows.Input.Key.U:
                    return MVVMInfrastructure.Key.U;
                case System.Windows.Input.Key.V:
                    return MVVMInfrastructure.Key.V;
                case System.Windows.Input.Key.W:
                    return MVVMInfrastructure.Key.W;
                case System.Windows.Input.Key.X:
                    return MVVMInfrastructure.Key.X;
                case System.Windows.Input.Key.Y:
                    return MVVMInfrastructure.Key.Y;
                case System.Windows.Input.Key.Z:
                    return MVVMInfrastructure.Key.Z;
                case System.Windows.Input.Key.LWin:
                    return MVVMInfrastructure.Key.LWin;
                case System.Windows.Input.Key.RWin:
                    return MVVMInfrastructure.Key.RWin;
                case System.Windows.Input.Key.Apps:
                    return MVVMInfrastructure.Key.Apps;
                case System.Windows.Input.Key.Sleep:
                    return MVVMInfrastructure.Key.Sleep;
                case System.Windows.Input.Key.NumPad0:
                    return MVVMInfrastructure.Key.NumPad0;
                case System.Windows.Input.Key.NumPad1:
                    return MVVMInfrastructure.Key.NumPad1;
                case System.Windows.Input.Key.NumPad2:
                    return MVVMInfrastructure.Key.NumPad2;
                case System.Windows.Input.Key.NumPad3:
                    return MVVMInfrastructure.Key.NumPad3;
                case System.Windows.Input.Key.NumPad4:
                    return MVVMInfrastructure.Key.NumPad4;
                case System.Windows.Input.Key.NumPad5:
                    return MVVMInfrastructure.Key.NumPad5;
                case System.Windows.Input.Key.NumPad6:
                    return MVVMInfrastructure.Key.NumPad6;
                case System.Windows.Input.Key.NumPad7:
                    return MVVMInfrastructure.Key.NumPad7;
                case System.Windows.Input.Key.NumPad8:
                    return MVVMInfrastructure.Key.NumPad8;
                case System.Windows.Input.Key.NumPad9:
                    return MVVMInfrastructure.Key.NumPad9;
                case System.Windows.Input.Key.Multiply:
                    return MVVMInfrastructure.Key.Multiply;
                case System.Windows.Input.Key.Add:
                    return MVVMInfrastructure.Key.Add;
                case System.Windows.Input.Key.Separator:
                    return MVVMInfrastructure.Key.Separator;
                case System.Windows.Input.Key.Subtract:
                    return MVVMInfrastructure.Key.Subtract;
                case System.Windows.Input.Key.Decimal:
                    return MVVMInfrastructure.Key.Decimal;
                case System.Windows.Input.Key.Divide:
                    return MVVMInfrastructure.Key.Divide;
                case System.Windows.Input.Key.F1:
                    return MVVMInfrastructure.Key.F1;
                case System.Windows.Input.Key.F2:
                    return MVVMInfrastructure.Key.F2;
                case System.Windows.Input.Key.F3:
                    return MVVMInfrastructure.Key.F3;
                case System.Windows.Input.Key.F4:
                    return MVVMInfrastructure.Key.F4;
                case System.Windows.Input.Key.F5:
                    return MVVMInfrastructure.Key.F5;
                case System.Windows.Input.Key.F6:
                    return MVVMInfrastructure.Key.F6;
                case System.Windows.Input.Key.F7:
                    return MVVMInfrastructure.Key.F7;
                case System.Windows.Input.Key.F8:
                    return MVVMInfrastructure.Key.F8;
                case System.Windows.Input.Key.F9:
                    return MVVMInfrastructure.Key.F9;
                case System.Windows.Input.Key.F10:
                    return MVVMInfrastructure.Key.F10;
                case System.Windows.Input.Key.F11:
                    return MVVMInfrastructure.Key.F11;
                case System.Windows.Input.Key.F12:
                    return MVVMInfrastructure.Key.F12;
                case System.Windows.Input.Key.F13:
                    return MVVMInfrastructure.Key.F13;
                case System.Windows.Input.Key.F14:
                    return MVVMInfrastructure.Key.F14;
                case System.Windows.Input.Key.F15:
                    return MVVMInfrastructure.Key.F15;
                case System.Windows.Input.Key.F16:
                    return MVVMInfrastructure.Key.F16;
                case System.Windows.Input.Key.F17:
                    return MVVMInfrastructure.Key.F17;
                case System.Windows.Input.Key.F18:
                    return MVVMInfrastructure.Key.F18;
                case System.Windows.Input.Key.F19:
                    return MVVMInfrastructure.Key.F19;
                case System.Windows.Input.Key.F20:
                    return MVVMInfrastructure.Key.F20;
                case System.Windows.Input.Key.F21:
                    return MVVMInfrastructure.Key.F21;
                case System.Windows.Input.Key.F22:
                    return MVVMInfrastructure.Key.F22;
                case System.Windows.Input.Key.F23:
                    return MVVMInfrastructure.Key.F23;
                case System.Windows.Input.Key.F24:
                    return MVVMInfrastructure.Key.F24;
                case System.Windows.Input.Key.NumLock:
                    return MVVMInfrastructure.Key.NumLock;
                case System.Windows.Input.Key.Scroll:
                    return MVVMInfrastructure.Key.Scroll;
                case System.Windows.Input.Key.LeftShift:
                    return MVVMInfrastructure.Key.LeftShift;
                case System.Windows.Input.Key.RightShift:
                    return MVVMInfrastructure.Key.RightShift;
                case System.Windows.Input.Key.LeftCtrl:
                    return MVVMInfrastructure.Key.LeftCtrl;
                case System.Windows.Input.Key.RightCtrl:
                    return MVVMInfrastructure.Key.RightCtrl;
                case System.Windows.Input.Key.LeftAlt:
                    return MVVMInfrastructure.Key.LeftAlt;
                case System.Windows.Input.Key.RightAlt:
                    return MVVMInfrastructure.Key.RightAlt;
                case System.Windows.Input.Key.BrowserBack:
                    return MVVMInfrastructure.Key.BrowserBack;
                case System.Windows.Input.Key.BrowserForward:
                    return MVVMInfrastructure.Key.BrowserForward;
                case System.Windows.Input.Key.BrowserRefresh:
                    return MVVMInfrastructure.Key.BrowserRefresh;
                case System.Windows.Input.Key.BrowserStop:
                    return MVVMInfrastructure.Key.BrowserStop;
                case System.Windows.Input.Key.BrowserSearch:
                    return MVVMInfrastructure.Key.BrowserSearch;
                case System.Windows.Input.Key.BrowserFavorites:
                    return MVVMInfrastructure.Key.BrowserFavorites;
                case System.Windows.Input.Key.BrowserHome:
                    return MVVMInfrastructure.Key.BrowserHome;
                case System.Windows.Input.Key.VolumeMute:
                    return MVVMInfrastructure.Key.VolumeMute;
                case System.Windows.Input.Key.VolumeDown:
                    return MVVMInfrastructure.Key.VolumeDown;
                case System.Windows.Input.Key.VolumeUp:
                    return MVVMInfrastructure.Key.VolumeUp;
                case System.Windows.Input.Key.MediaNextTrack:
                    return MVVMInfrastructure.Key.MediaNextTrack;
                case System.Windows.Input.Key.MediaPreviousTrack:
                    return MVVMInfrastructure.Key.MediaPreviousTrack;
                case System.Windows.Input.Key.MediaStop:
                    return MVVMInfrastructure.Key.MediaStop;
                case System.Windows.Input.Key.MediaPlayPause:
                    return MVVMInfrastructure.Key.MediaPlayPause;
                case System.Windows.Input.Key.LaunchMail:
                    return MVVMInfrastructure.Key.LaunchMail;
                case System.Windows.Input.Key.SelectMedia:
                    return MVVMInfrastructure.Key.SelectMedia;
                case System.Windows.Input.Key.LaunchApplication1:
                    return MVVMInfrastructure.Key.LaunchApplication1;
                case System.Windows.Input.Key.LaunchApplication2:
                    return MVVMInfrastructure.Key.LaunchApplication2;
                //case System.Windows.Input.Key.Oem1:
                //    break;
                //case System.Windows.Input.Key.OemSemicolon:
                //    break;
                //case System.Windows.Input.Key.OemPlus:
                //    break;
                //case System.Windows.Input.Key.OemComma:
                //    break;
                //case System.Windows.Input.Key.OemMinus:
                //    break;
                //case System.Windows.Input.Key.OemPeriod:
                //    break;
                //case System.Windows.Input.Key.Oem2:
                //    break;
                //case System.Windows.Input.Key.OemQuestion:
                //    break;
                //case System.Windows.Input.Key.Oem3:
                //    break;
                //case System.Windows.Input.Key.OemTilde:
                //    break;
                //case System.Windows.Input.Key.AbntC1:
                //    break;
                //case System.Windows.Input.Key.AbntC2:
                //    break;
                //case System.Windows.Input.Key.Oem4:
                //    break;
                //case System.Windows.Input.Key.OemOpenBrackets:
                //    break;
                //case System.Windows.Input.Key.Oem5:
                //    break;
                //case System.Windows.Input.Key.OemPipe:
                //    break;
                //case System.Windows.Input.Key.Oem6:
                //    break;
                //case System.Windows.Input.Key.OemCloseBrackets:
                //    break;
                //case System.Windows.Input.Key.Oem7:
                //    break;
                //case System.Windows.Input.Key.OemQuotes:
                //    break;
                //case System.Windows.Input.Key.Oem8:
                //    break;
                //case System.Windows.Input.Key.Oem102:
                //    break;
                //case System.Windows.Input.Key.OemBackslash:
                //    break;
                case System.Windows.Input.Key.ImeProcessed:
                    return MVVMInfrastructure.Key.ImeProcessed;
                case System.Windows.Input.Key.System:
                    return MVVMInfrastructure.Key.System;
                //case System.Windows.Input.Key.OemAttn:
                //    break;
                //case System.Windows.Input.Key.DbeAlphanumeric:
                //    break;
                //case System.Windows.Input.Key.OemFinish:
                //    break;
                //case System.Windows.Input.Key.DbeKatakana:
                //    break;
                //case System.Windows.Input.Key.OemCopy:
                //    break;
                //case System.Windows.Input.Key.DbeHiragana:
                //    break;
                //case System.Windows.Input.Key.OemAuto:
                //    break;
                //case System.Windows.Input.Key.DbeSbcsChar:
                //    break;
                //case System.Windows.Input.Key.OemEnlw:
                //    break;
                //case System.Windows.Input.Key.DbeDbcsChar:
                //    break;
                //case System.Windows.Input.Key.OemBackTab:
                //    break;
                //case System.Windows.Input.Key.DbeRoman:
                //    break;
                //case System.Windows.Input.Key.Attn:
                //    break;
                //case System.Windows.Input.Key.DbeNoRoman:
                //    break;
                //case System.Windows.Input.Key.CrSel:
                //    break;
                //case System.Windows.Input.Key.DbeEnterWordRegisterMode:
                //    break;
                //case System.Windows.Input.Key.ExSel:
                //    break;
                //case System.Windows.Input.Key.DbeEnterImeConfigureMode:
                //    break;
                //case System.Windows.Input.Key.EraseEof:
                //    break;
                //case System.Windows.Input.Key.DbeFlushString:
                //    break;
                case System.Windows.Input.Key.Play:
                    return MVVMInfrastructure.Key.Play;
                //case System.Windows.Input.Key.DbeCodeInput:
                //    break;
                case System.Windows.Input.Key.Zoom:
                    return MVVMInfrastructure.Key.Zoom;
                //case System.Windows.Input.Key.DbeNoCodeInput:
                //    break;
                //case System.Windows.Input.Key.NoName:
                //    break;
                //case System.Windows.Input.Key.DbeDetermineString:
                //    break;
                case System.Windows.Input.Key.Pa1:
                    return MVVMInfrastructure.Key.Pa1;
                //case System.Windows.Input.Key.DbeEnterDialogConversionMode:
                //    break;
                // System.Windows.Input.Key.OemClear:
                //    return MVVMInfrastructure.Key.OemClear;
                //case System.Windows.Input.Key.DeadCharProcessed:
                //    return
                default:
                    throw new Exception();

            }

            throw new Exception();
        }
    }
}
